"""Public sensor-preprocessing models and pipeline interfaces."""

from .capture_reader import CaptureSessionReader, CaptureSessionReadError
from .clock_mapping import (
    ClockMappingSegment,
    SegmentedClockMapper,
    TimestampOutOfRangeError,
    client_perf_source_instance_id,
    frame_callback_observation,
    frame_presentation_observation,
    frame_sdk_observation,
    glasses_elapsed_source_instance_id,
    imu_sensor_event_observation,
    mp4_source_instance_id,
    rokid_sdk_source_instance_id,
    rtp_match_error_to_uncertainty_ns,
)
from .imu_orientation import (
    ImuOrientationConfig,
    ImuOrientationFilter,
    quaternion_to_euler_degrees,
)
from .imu_pose import (
    RecordedImuPose,
    RecordedImuPoseTimeline,
    build_recorded_imu_pose_timeline,
)
from .models import (
    AlignmentStatus,
    CaptureClipRef,
    CaptureSessionRef,
    ClockId,
    ImuSensorType,
    MetadataMatchStatus,
    Mp4Timestamp,
    RawFrameRef,
    RawImuSample,
    StoredAlignment,
    TimeEstimate,
    TimeObservation,
    TimestampSemantic,
    TimeStatus,
)
from .pipeline import (
    CalibrationProvenance,
    ImagePreprocessingConfig,
    ImuCalibration,
    LiveFrameInput,
    LiveImuInput,
    LivePreprocessingConfig,
    PreparedFrameBundle,
    PreparedImuSample,
    RecordedPreprocessingConfig,
    SensorCalibration,
    SensorPreprocessingConfig,
    SensorPreprocessingError,
    SensorPreprocessingPipeline,
)
from .recorded_alignment import (
    RecordedAlignmentError,
    RecordedClockMapping,
    derive_recorded_clock_mapping,
    persist_recorded_clock_mapping,
)

__all__ = [
    "AlignmentStatus",
    "CaptureClipRef",
    "CaptureSessionReadError",
    "CaptureSessionReader",
    "CaptureSessionRef",
    "CalibrationProvenance",
    "ClockId",
    "ClockMappingSegment",
    "ImuSensorType",
    "ImuOrientationConfig",
    "ImuOrientationFilter",
    "ImuCalibration",
    "ImagePreprocessingConfig",
    "LiveFrameInput",
    "LiveImuInput",
    "LivePreprocessingConfig",
    "MetadataMatchStatus",
    "Mp4Timestamp",
    "PreparedFrameBundle",
    "PreparedImuSample",
    "RecordedPreprocessingConfig",
    "RecordedImuPose",
    "RecordedImuPoseTimeline",
    "RawFrameRef",
    "RawImuSample",
    "RecordedAlignmentError",
    "RecordedClockMapping",
    "StoredAlignment",
    "TimeEstimate",
    "TimeObservation",
    "TimeStatus",
    "TimestampOutOfRangeError",
    "TimestampSemantic",
    "SegmentedClockMapper",
    "SensorCalibration",
    "SensorPreprocessingConfig",
    "SensorPreprocessingError",
    "SensorPreprocessingPipeline",
    "client_perf_source_instance_id",
    "derive_recorded_clock_mapping",
    "build_recorded_imu_pose_timeline",
    "quaternion_to_euler_degrees",
    "frame_callback_observation",
    "frame_presentation_observation",
    "frame_sdk_observation",
    "glasses_elapsed_source_instance_id",
    "imu_sensor_event_observation",
    "mp4_source_instance_id",
    "persist_recorded_clock_mapping",
    "rokid_sdk_source_instance_id",
    "rtp_match_error_to_uncertainty_ns",
]
