from __future__ import annotations

import string
from enum import StrEnum
from typing import Self
from urllib.parse import quote

from pydantic import BaseModel, ConfigDict, Field, SecretStr, field_validator, model_validator


class RtspTransport(StrEnum):
    TCP = "tcp"
    UDP = "udp"


class IngestPhase(StrEnum):
    IDLE = "idle"
    PROBING = "probing"
    READY = "ready"
    FAILED = "failed"


class RtspSourceConfig(BaseModel):
    """Connection settings for the RTSP URL generated by a GB28181 platform."""

    model_config = ConfigDict(extra="forbid")

    host: str = Field(min_length=1, max_length=253)
    port: int = Field(default=554, ge=1, le=65535)
    device_id: str = Field(min_length=1, max_length=64, pattern=r"^[A-Za-z0-9_.-]+$")
    channel_id: str | None = Field(default=None, max_length=64, pattern=r"^[A-Za-z0-9_.-]+$")
    username: str | None = Field(default=None, max_length=128)
    password: SecretStr | None = None
    transport: RtspTransport = RtspTransport.TCP
    open_timeout_ms: int = Field(default=5000, ge=250, le=60_000)
    read_timeout_ms: int = Field(default=5000, ge=250, le=60_000)

    @field_validator("host")
    @classmethod
    def validate_host(cls, value: str) -> str:
        normalized = value.strip()
        allowed = frozenset(string.ascii_letters + string.digits + ".:-")
        if not normalized or any(character not in allowed for character in normalized):
            raise ValueError("host must be a DNS name or an unbracketed IP address")
        return normalized

    @model_validator(mode="after")
    def validate_credentials(self) -> Self:
        if self.password is not None and not self.username:
            raise ValueError("username is required when password is provided")
        return self

    @property
    def resolved_channel_id(self) -> str:
        return self.channel_id or self.device_id

    @property
    def stream_path(self) -> str:
        return f"/rtp/{self.device_id}_{self.resolved_channel_id}"

    @property
    def rtsp_url(self) -> str:
        credentials = ""
        if self.username:
            credentials = quote(self.username, safe="")
            if self.password is not None:
                credentials += f":{quote(self.password.get_secret_value(), safe='')}"
            credentials += "@"
        host = f"[{self.host}]" if ":" in self.host and not self.host.startswith("[") else self.host
        return f"rtsp://{credentials}{host}:{self.port}{self.stream_path}"

    @property
    def redacted_url(self) -> str:
        host = f"[{self.host}]" if ":" in self.host and not self.host.startswith("[") else self.host
        return f"rtsp://{host}:{self.port}{self.stream_path}"


class ProbeResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: str = "1.0"
    source_kind: str = "rokid-gb28181-rtsp"
    redacted_url: str
    transport: RtspTransport
    codec: str
    width: int = Field(gt=0)
    height: int = Field(gt=0)
    pixel_format: str
    average_fps: float | None = Field(default=None, ge=0)
    first_frame_pts: int | None = None
    first_frame_time_base_num: int | None = None
    first_frame_time_base_den: int | None = None
    opened_at_unix_ns: int = Field(gt=0)
    first_frame_received_at_perf_counter_ns: int = Field(gt=0)
    probe_latency_ms: float = Field(ge=0)


class IngestStatus(BaseModel):
    model_config = ConfigDict(extra="forbid")

    service_version: str = "0.1.0"
    phase: IngestPhase
    last_error: str | None = None
    last_probe: ProbeResult | None = None
